### PR TITLE
DYNAMIC TIME YEET

### PR DESCRIPTION
**Pull request by Objectivitix**
please don't blindly approve, view code first even tho we tested it like a million times

### CODE REVIEW

**Review by AbooMinister25 — APPROVED** [review]
Everything looks good, approved :D

**Comment by Objectivitix** [comment]
no one gonna review this?!

**Comment by AbooMinister25** [comment]
> please don't blindly approve, view code first even tho we tested it like a million times

~~totally didnt blindly review~~

**Comment by Objectivitix** [comment]
my patience ->    ______________________

(it's thin lol)

**Comment by Objectivitix** [comment]
merging

**Comment by dawnofmidnight** [comment]
I thought we were waiting for two approvals

**Pull request merged**
